# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[debug]
log_level = "debug"

[release.proxy]
proxy_assets = false
allowed_endpoints = [ "/intermodal", "/guesser", "/address",
                      "/railviz/get_trains", "/railviz/get_trips", "/railviz/get_station",
                      "/lookup/schedule_info", "/gbfs/info", "/ppr/route", "/trip_to_connection" ]


[debug.proxy]
proxy_assets = true
motis_address = "https://europe.motis-project.de"
routes_per_minute_limit = 20
