# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Install motis-proxy executable
  get_url:
    url: https://github.com/public-transport/transitous/releases/download/motis-proxy-v0.3.0/motis-proxy
    dest: /usr/local/bin/motis-proxy
    mode: '0777'

- name: Create motis-proxy runtime directory
  file:
    path: /var/lib/motis-proxy/
    state: directory

- name: Copy motis-proxy config file
  copy:
    src: Rocket.toml
    dest: /var/lib/motis-proxy/Rocket.toml

- name: Copy motis-proxy systemd unit
  copy:
    src: motis-proxy.service
    dest: /etc/systemd/system/motis-proxy.service

- name: Enable motis-proxy systemd service
  systemd:
    name: motis-proxy.service
    enabled: true
    state: started
    masked: false
    daemon_reload: true
