# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

server:
  host: 0.0.0.0
  port: 8080
  web_folder: "/opt/motis/ui/"  # Just for testing, not used on server
  data_attribution_link: https://transitous.org/sources/

street_routing:
  elevation_data_dir: ./srtm/
osr_footpath: true
elevators: false
geocoding: true
reverse_geocoding: true

osm: planet-latest.osm.pbf

tiles:
  profile: /opt/motis/tiles-profiles/full.lua
  coastline: land-polygons-complete-4326.zip

timetable:
  first_day: -100
  num_days: 465
  railviz: true
  with_shapes: true
  ignore_errors: true
  adjust_footpaths: true
  merge_dupes_intra_src: true
  merge_dupes_inter_src: true
  link_stop_distance: 100
  update_interval: 60
  http_timeout: 30
  incremental_rt_update: false
  max_footpath_length: 12
  extend_missing_footpaths: true
  preprocess_max_matching_distance: 250
# The datasets are filled in by ./src/generate-motis-config.py
  datasets:

gbfs:
  feeds:

limits:
  stoptimes_max_results: 16384
  plan_max_results: 256
  plan_max_search_window_minutes: 5760
  stops_max_results: 2048
  onetoall_max_results: 524288
  onetoall_max_travel_minutes: 2880
  routing_max_timeout_seconds: 90
