# SPDX-FileCopyrightText: 2025 Traines <git@traines.eu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# These are encrypted with the feed proxy vault password, not with the main vault password
ch-opentransportdataswiss25-0:
  headers:
    Authorization: !vault |
          $ANSIBLE_VAULT;1.1;AES256;feed-proxy
          63343464323064313632306138646134656561653236663361326137626161323630343165353631
          3761656365656363613430663534663536633234373266630a383238636463663063646536623533
          31326330393532373339303239326235396530316638356137323538393265343234626335373833
          3433633530353663320a636130613138656233346332643732666335623862393737363962316662
          35393935633931366266316532306232306366313531656635333031393137326533343932626162
          36393034363330303061393861316233643137623262636264653133666338383530663636653032
          386466383261353561663732356630373332

ch-opentransportdataswiss25-1:
  headers:
    Authorization: !vault |
          $ANSIBLE_VAULT;1.1;AES256;feed-proxy
          36356137613066643030633038363766306537343933333835373038613336626232323038643964
          6563323464666235386338393232626435666136646237350a336532646236386666313634326362
          63363532376362326666613134313862303831396635326237346363383565613530393435373063
          6266383863613136330a393866333530356261623735636636626161396231363932646361326336
          61643135393433393931623736336630643936616330393038323734343765356466616636653036
          64643932393230623666663663653131356363313931373938376534643230666435303337643266
          37373033376665626538393265306139383233393963633165613138376530306233613163303462
          66616233626534303637623866663130326439646531373930393835653736306561353731646233
          32326265613139626633653632626332316533316238363564613938336633326331316664303333
          6332633430643833373139323138326532323866306137633363

eu-citybikes:
  gbfs: true
  url: https://api.citybik.es/gbfs/3/manifest.json
  headers:
    x-api-key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;feed-proxy
          64643338373133393530663963653736656133313733666566643934303435663664363737633263
          3430636234336139313161653238383636396238343732370a623764333433336564396561323262
          62333339393431373935666535666134636238353030653031633932646431613839663662376631
          3230643632616633380a383765356131353636623631396262333831343263333935613535323462
          64656134353934633435333964636533356233653865353033636261356336343363323766313233
          6163333738643133353336336338306236623365666466346532