# SPDX-FileCopyrightText: 2025 Traines <git@traines.eu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# This is encrypted with the main vault password
feed_secrets_vault_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36323762383663333736313764376330336562363839663735326430373465636666653137663266
          6538663262633632663836373235333332386232376337360a663834303264616366323232326435
          33303166633432373763383933643831353733346338336132616532643066343762396638666465
          6239306633656333630a393364386466653439333163646161353466626638643530653331396331
          39323530356338396530643131343961396133356534323265363861633265323864323864386535
          6539333363636231346138353836653739633964616633663561