# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Set up MOTIS servers
  hosts: motis
  roles:
    - rsync
    - motis
    - motis-proxy
    - nginx
