# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Install docker
  apt:
    name: docker.io

- name: Enable docker service
  systemd:
    name: docker
    enabled: true
    state: started
    masked: false

- name: Copy woodpecker-agent executable
  apt:
    deb: https://github.com/woodpecker-ci/woodpecker/releases/download/v2.4.0/woodpecker-agent_linux_amd64.tar.gz

- name: Create woodpecker-agent user
  user:
    name: woodpecker-agent
    comment: Woodpecker CI user

- name: Set up woodpecker agent systemd service
  template:
    dest: /etc/systemd/system/woodpecker-agent.service
    src: woodpecker-agent.service.j2
    owner: root
    group: root
    mode: '0644'

- name: Create cache directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/cache/transitous/downloads/
    - /var/cache/transitous/out/

- name: Enable woodpecker service
  systemd:
    name: woodpecker-agent.service
    enabled: true
    state: started
    masked: false
    daemon_reload: true
