# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

name: Verfy new data can be imported

on: [pull_request]

jobs:
  test-import:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Fetch branches and submodules
      run: git fetch --unshallow && git fetch --all && git submodule update --init --checkout --remote
    - name: Build docker images
      run: docker build -t transitous . -f ci/container/Containerfile
    - name: Verify that new feeds can be downloaded and parsed
      run: |
        chmod 777 .
        docker run -v $PWD:/transitous -w /transitous transitous ci/fetch-feeds.py merge-request
