# SPDX-FileCopyrightText: 2024 Jonah Br√ºchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

name: Verify new data can be imported

on:
  pull_request:
    paths:
      - "feeds/**"

jobs:
  test-import:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Fetch branches and submodules
      run: git fetch --unshallow && git fetch --all && git submodule update --init --checkout --remote
    - name: Build docker images
      run: docker build -t transitous . -f ci/container/Containerfile
    - name: regenerate austria and france
      run: |
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-austria.py
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-france.py
        if [[ -n $(git status --porcelain) ]]; then
              git checkout -B work/transitous-bot/regenerate-feeds
              git add feeds/fr.json feeds/at.json
              git commit -m "Update generated feeds"
              gh pr create -B work/transitous-bot/regenerate-feedsRegenerate -H main --title 'Update French or Austria feeds' --body 'Created by Github action' 
        fi
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Verify that new feeds can be downloaded and parsed
      run: |
        find . -type d -exec chmod 777 {} \;
        docker run -v $PWD:/transitous -w /transitous transitous ci/fetch-feeds.py merge-request
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-motis-config.py full
